"""Central application-level domain constants."""

from decimal import Decimal

SUBSTANTIVE_CERTIFICATE_AMOUNT = 10000

MAX_PROFIT_COST_POA_CLAIM_COUNT = 4
MIN_MONTHS_BEFORE_PROFIT_COST_POA = 3
AUTO_APPROVAL_MAX_TOTAL = Decimal("50000.00")

PROFIT_COST_PAYMENT_RATE = Decimal("0.8")
VAT_MULTIPLIER = Decimal("1.2")
