import enum


class ClaimErrorCode(str, enum.Enum):
    MISSING_TOTAL_CLAIM_COST = "MISSING_TOTAL_CLAIM_COST"
    MISSING_NON_PROFIT_COST_TOTAL = "MISSING_NON_PROFIT_COST_TOTAL"
    MISSING_GROSS_TOTAL_WHEN_NET_ENTERED = "MISSING_GROSS_TOTAL_WHEN_NET_ENTERED"
    PROFIT_COST_MIXED_VAT = "PROFIT_COST_MIXED_VAT"
    NET_TOTAL_HIGHER_THAN_GROSS_TOTAL = "NET_TOTAL_HIGHER_THAN_GROSS_TOTAL"
    NEGATIVE_NET_COST = "NEGATIVE_NET_COST"
    MISSING_POA_TYPE_FOR_PAYMENT_ON_ACCOUNT = "MISSING_POA_TYPE_FOR_PAYMENT_ON_ACCOUNT"
    POA_TYPE_NOT_ALLOWED_FOR_NON_PAYMENT_ON_ACCOUNT = (
        "POA_TYPE_NOT_ALLOWED_FOR_NON_PAYMENT_ON_ACCOUNT"
    )
    MISSING_CLAIM_EVIDENCE = "MISSING_CLAIM_EVIDENCE"
    APPLICATION_NOT_GRANTED = "APPLICATION_NOT_GRANTED"
    MISSING_INQUEST_OUTCOMES = "MISSING_INQUEST_OUTCOMES"
    INQUEST_OUTCOMES_NOT_ALLOWED = "INQUEST_OUTCOMES_NOT_ALLOWED"
    MISSING_COST_TEMPLATE_FILE = "MISSING_COST_TEMPLATE_FILE"
    COST_TEMPLATE_FILE_NOT_ALLOWED = "COST_TEMPLATE_FILE_NOT_ALLOWED"
    MISSING_FINAL_BILL_DETAILS = "MISSING_FINAL_BILL_DETAILS"
    FINAL_BILL_DETAILS_NOT_ALLOWED = "FINAL_BILL_DETAILS_NOT_ALLOWED"


class ClaimValidationError(Exception):
    def __init__(self, code: ClaimErrorCode, message: str) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
