"""IDDS-375: Add certificate dates

Revision ID: 02a055ebbdc7
Revises: a3d55c2072d7
Create Date: 2026-07-03 16:28:43.998884

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "02a055ebbdc7"
down_revision: Union[str, None] = "a3d55c2072d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application_proceeding",
        sa.Column("certificate_issue_date", sa.Date(), nullable=True),
    )
    op.add_column(
        "application_proceeding",
        sa.Column("certificate_start_date", sa.Date(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application_proceeding", "certificate_start_date")
    op.drop_column("application_proceeding", "certificate_issue_date")
    # ### end Alembic commands ###
