"""Create history event table

Revision ID: 0588fd6aba84
Revises: 9c0ab4f5baa3
Create Date: 2026-08-10 14:18:52.339861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0588fd6aba84'
down_revision: Union[str, None] = '9c0ab4f5baa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_reference', 
              sa.Enum(
                  'APPLICATION_SUBMITTED', 
                  'APPLICATION_ASSESSMENT_COMPLETED', 
                  'CERTIFICATE_CREATED', 
                  'INTERESTED_PARTY_UPDATED', 
                  'CLAIM_SUBMITTED', 
                  'CLAIM_ASSESSMENT_COMPLETED', 
                  'POA_AUTO_APPROVED', 
                  'POA_AUTO_REJECTED', 
                  'APPLICATION_SUBMISSION_CONFIRMATION', 
                  'APPLICATION_GRANTED_EMAIL', 
                  'APPLICATION_GRANTED_LETTER', 
                  'APPLICATION_REFUSED', 
                  'CLAIM_SUBMISSION_CONFIRMATION', 
                  'CLAIM_APPROVED_EMAIL', 
                  name='historyeventreference'),
            nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_type', sa.Enum('SYSTEM', 'CASEWORKER', 'PROVIDER', name='actortype'), nullable=False),
    sa.Column('event_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('laa_reference', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['laa_reference'], ['application.laa_reference'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history_event')
    # ### end Alembic commands ###
