"""make claim cost fields nullable and add vat zero

Revision ID: 0c9b1491b27e
Revises: da57ddca1aae
Create Date: 2026-07-13 13:55:27.835289

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0c9b1491b27e"
down_revision: Union[str, None] = "da57ddca1aae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "claim", sa.Column("total_profit_cost_vat_zero", sa.Integer(), nullable=True)
    )
    op.alter_column(
        "claim", "total_profit_cost_net", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "claim", "total_profit_cost_gross", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "claim", "total_profit_cost_gross", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "claim", "total_profit_cost_net", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("claim", "total_profit_cost_vat_zero")
    # ### end Alembic commands ###
