"""IDDS-609 add claim_decision_amount table

Revision ID: 2157b7f59c80
Revises: a8af37d3552a
Create Date: 2026-09-09 14:56:26.104902

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2157b7f59c80"
down_revision: str | None = "a8af37d3552a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "claim_decision_amount",
        sa.Column("claim_decision_amount_id", sa.Integer(), nullable=False),
        sa.Column("claim_decision_id", sa.Integer(), nullable=False),
        sa.Column("profit_cost_net", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "profit_cost_gross", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column(
            "profit_cost_vat_zero", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column("disbursement_net", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "disbursement_gross", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column(
            "disbursement_vat_zero", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["claim_decision_id"],
            ["claim_decision.claim_decision_id"],
        ),
        sa.PrimaryKeyConstraint("claim_decision_amount_id"),
        sa.UniqueConstraint("claim_decision_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("claim_decision_amount")
    # ### end Alembic commands ###

