"""Add coroners letter to application

Revision ID: 3e4a560da60d
Revises: df44b19af78e
Create Date: 2026-06-18 11:42:30.093826

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "3e4a560da60d"
down_revision: Union[str, None] = "df44b19af78e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coroners_letter",
        sa.Column("coroners_letter_id", sa.Integer(), nullable=False),
        sa.Column("sds_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("coroners_letter_id"),
    )
    op.add_column(
        "application", sa.Column("coroners_letter_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None,
        "application",
        "coroners_letter",
        ["coroners_letter_id"],
        ["coroners_letter_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "application", type_="foreignkey")
    op.drop_column("application", "coroners_letter_id")
    op.drop_table("coroners_letter")
    # ### end Alembic commands ###
