"""Move is_client_correspondence_recipient

Revision ID: 453bd88d49af
Revises: 81265492c319
Create Date: 2026-05-29 16:43:24.983774

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "453bd88d49af"
down_revision: Union[str, None] = "81265492c319"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application", "is_client_correspondence_recipient")
    op.add_column(
        "client",
        sa.Column("is_client_correspondence_recipient", sa.Boolean(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client", "is_client_correspondence_recipient")
    op.add_column(
        "application",
        sa.Column(
            "is_client_correspondence_recipient",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
