"""IDDS-427-add-indexes

Revision ID: 4a69570166d5
Revises: 072b60aa9b4e
Create Date: 2026-09-07 15:18:29.203093

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4a69570166d5"
down_revision: Union[str, None] = "072b60aa9b4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_application", "application", ["laa_reference"], unique=True)
    op.create_index(
        "ix_application_proceeding_merits_decision",
        "application_proceeding",
        ["merits_decision"],
        unique=False,
    )
    op.create_index("ix_claim_application_id", "claim", ["application_id"], unique=False)
    op.create_index(
        "ix_claim_status_id_submission_date",
        "claim",
        ["status_id", "submission_date"],
        unique=False,
    )
    op.create_index(
        "ix_claim_decision_claim_id",
        "claim_decision",
        ["claim_id"],
        unique=False,
    )
    op.create_index(
        "ix_history_event_application_id_timestamp",
        "history_event",
        ["application_id", "timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_history_event_application_id_timestamp", table_name="history_event")
    op.drop_index("ix_claim_decision_claim_id", table_name="claim_decision")
    op.drop_index("ix_claim_status_id_submission_date", table_name="claim")
    op.drop_index("ix_claim_application_id", table_name="claim")
    op.drop_index("ix_application_proceeding_merits_decision", table_name="application_proceeding")
    op.drop_index("ix_application", table_name="application")
    # ### end Alembic commands ###
