"""idds_652_add_entra_user_object_id_to_history_event

Revision ID: 595d977552b0
Revises: c4f1a2b3d5e6
Create Date: 2026-08-18 16:54:14.484320

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "595d977552b0"
down_revision: Union[str, None] = "c4f1a2b3d5e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "history_event",
        sa.Column(
            "entra_user_object_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("history_event", "entra_user_object_id")
    # ### end Alembic commands ###
