"""idds_402_convert_claim_totals_to_numeric

Revision ID: 59ab5b5eacce
Revises: 0c9b1491b27e
Create Date: 2026-07-14 16:08:10.838590

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "59ab5b5eacce"
down_revision: Union[str, None] = "0c9b1491b27e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "claim",
        "total_profit_cost_net",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "claim",
        "total_profit_cost_gross",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "claim",
        "total_profit_cost_vat_zero",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "claim",
        "total_profit_cost_vat_zero",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "claim",
        "total_profit_cost_gross",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "claim",
        "total_profit_cost_net",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
