"""empty message

Revision ID: 5ebd34a076f5
Revises: c0cec51e7a4f
Create Date: 2026-06-24 13:41:43.486896

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "5ebd34a076f5"
down_revision: Union[str, None] = "c0cec51e7a4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "application",
        "coroners_letter_id",
        existing_type=sa.INTEGER(),
        type_=sa.Uuid(),
        existing_nullable=True,
    )
    op.add_column(
        "coroners_letter",
        sa.Column("sds_file_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.alter_column(
        "coroners_letter",
        "coroners_letter_id",
        existing_type=sa.INTEGER(),
        type_=sa.Uuid(),
        existing_nullable=False,
        existing_server_default=sa.text(
            "nextval('coroners_letter_coroners_letter_id_seq'::regclass)"
        ),
    )
    op.drop_column("coroners_letter", "sds_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "coroners_letter",
        sa.Column("sds_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "coroners_letter",
        "coroners_letter_id",
        existing_type=sa.Uuid(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        existing_server_default=sa.text(
            "nextval('coroners_letter_coroners_letter_id_seq'::regclass)"
        ),
    )
    op.drop_column("coroners_letter", "sds_file_name")
    op.alter_column(
        "application",
        "coroners_letter_id",
        existing_type=sa.Uuid(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
