"""empty message

Revision ID: 5ebd34a076f5
Revises: c0cec51e7a4f
Create Date: 2026-06-24 13:41:43.486896

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5ebd34a076f5"
down_revision: Union[str, None] = "c0cec51e7a4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename the sds_id column in the coroners_letter table to sds_file_name
    op.alter_column("coroners_letter", "sds_id", new_column_name="sds_file_name")

    # Drop the coroners_letter_id column from both tables
    op.drop_column("application", "coroners_letter_id")
    op.drop_column("coroners_letter", "coroners_letter_id")

    # Add a new coroners_letter_id column to the coroners_letter table with a UUID type and set it as the primary key
    op.add_column(
        "coroners_letter",
        sa.Column(
            "coroners_letter_id",
            sa.Uuid(),
            nullable=False,
            server_default=sa.text("gen_random_uuid()"),
            primary_key=True,
            unique=True,
        ),
    )
    # Add the coroners_letter_id column in the application table to be of type UUID and nullable
    op.add_column(
        "application",
        sa.Column(
            "coroners_letter_id",
            sa.Uuid(),
            sa.ForeignKey("coroners_letter.coroners_letter_id"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("coroners_letter", "sds_file_name", new_column_name="sds_id")

    op.drop_column("application", "coroners_letter_id")
    op.drop_column("coroners_letter", "coroners_letter_id")

    op.add_column(
        "coroners_letter",
        sa.Column(
            "coroners_letter_id",
            sa.Integer(),
            nullable=False,
            server_default=sa.text(
                "nextval('coroners_letter_coroners_letter_id_seq'::regclass)"
            ),
            primary_key=True,
            unique=True,
        ),
    )
    op.add_column(
        "application",
        sa.Column(
            "coroners_letter_id",
            sa.Integer(),
            sa.ForeignKey("coroners_letter.coroners_letter_id"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
