"""Add cost limitation effective date and certificate end date to application proceeding

Revision ID: 6001ea88742d
Revises: c4f1a2b3d5e6
Create Date: 2026-08-19 10:35:38.047023

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6001ea88742d"
down_revision: str | None = "c4f1a2b3d5e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application_proceeding",
        sa.Column(
            "substantive_cost_limitation_effective_date", sa.Date(), nullable=True
        ),
    )
    op.add_column(
        "application_proceeding",
        sa.Column("certificate_end_date", sa.Date(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application_proceeding", "certificate_end_date")
    op.drop_column(
        "application_proceeding", "substantive_cost_limitation_effective_date"
    )
    # ### end Alembic commands ###
