"""Move correspondence_recipient

Revision ID: 6b0bce71fdb8
Revises: 453bd88d49af
Create Date: 2026-06-05 17:04:16.720485

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6b0bce71fdb8"
down_revision: Union[str, None] = "453bd88d49af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application", "correspondence_recipient_type")
    op.drop_column("application", "correspondence_recipient_name")
    op.add_column(
        "client",
        sa.Column(
            "correspondence_recipient_type",
            sa.Enum("PERSON", "ORGANISATION", name="correspondencerecipienttype"),
            nullable=True,
        ),
    )
    op.add_column(
        "client",
        sa.Column(
            "correspondence_recipient_name",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client", "correspondence_recipient_name")
    op.drop_column("client", "correspondence_recipient_type")
    op.add_column(
        "application",
        sa.Column(
            "correspondence_recipient_name",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "application",
        sa.Column(
            "correspondence_recipient_type",
            postgresql.ENUM(
                "PERSON", "ORGANISATION", name="correspondencerecipienttype"
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
