"""add_email_to_provider

Revision ID: 7a4f5f615543
Revises: df44b19af78e
Create Date: 2026-06-17 14:09:39.763580

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "7a4f5f615543"
down_revision: Union[str, None] = "df44b19af78e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "provider",
        sa.Column("email_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("provider", "email_address")
    # ### end Alembic commands ###
