"""add claim_cost_template table

Revision ID: 965237adae9c
Revises: a7c3e9f1b2d4
Create Date: 2026-08-26 11:54:02.535265

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "965237adae9c"
down_revision: str | None = "a7c3e9f1b2d4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "claim_cost_template",
        sa.Column("claim_cost_template_id", sa.Integer(), nullable=False),
        sa.Column("claim_id", sa.Integer(), nullable=False),
        sa.Column("claim_cost_template_file_id", sa.Uuid(), nullable=False),
        sa.Column(
            "claim_cost_template_file_name",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claim.claim_id"],
        ),
        sa.PrimaryKeyConstraint("claim_cost_template_id"),
        sa.UniqueConstraint("claim_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("claim_cost_template")
    # ### end Alembic commands ###
