"""add claim_id fk to claim_evidence

Revision ID: 9c0ab4f5baa3
Revises: 46d24adfe893
Create Date: 2026-07-29 15:30:38.442713

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9c0ab4f5baa3"
down_revision: Union[str, None] = "46d24adfe893"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("claim_evidence", sa.Column("claim_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "claim_evidence", "claim", ["claim_id"], ["claim_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "claim_evidence", type_="foreignkey")
    op.drop_column("claim_evidence", "claim_id")
    # ### end Alembic commands ###
