"""Update cost limit to 10000

Revision ID: a0d64e7bd954
Revises: 02a055ebbdc7
Create Date: 2026-07-08 13:56:15.497630

"""

from typing import Sequence, Union
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a0d64e7bd954"
down_revision: Union[str, None] = "02a055ebbdc7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE proceeding SET substantive_cost_limitation = 10000;")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
