"""IDDS-375 remove overall_decision column make it calculated

Revision ID: a3d55c2072d7
Revises: 5ebd34a076f5
Create Date: 2026-07-03 12:06:04.180837

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a3d55c2072d7"
down_revision: Union[str, None] = "5ebd34a076f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application", "overall_decision")
    op.execute(
        "UPDATE application_proceeding SET merits_decision = 'PENDING' WHERE merits_decision IS NULL"
    )
    op.alter_column(
        "application_proceeding",
        "merits_decision",
        existing_type=sa.VARCHAR(),
        nullable=False,
        server_default="PENDING",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "application_proceeding",
        "merits_decision",
        existing_type=sa.VARCHAR(),
        nullable=True,
        server_default=None,
    )
    op.add_column(
        "application",
        sa.Column("overall_decision", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
