"""idds_706_add_claim_inquest_outcome

Revision ID: a7c3e9f1b2d4
Revises: 6001ea88742d
Create Date: 2026-08-26 09:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a7c3e9f1b2d4"
down_revision: Union[str, None] = "fa5e3308e150"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "claim_inquest_outcome",
        sa.Column("claim_inquest_outcome_id", sa.Integer(), nullable=False),
        sa.Column("claim_id", sa.Integer(), nullable=False),
        sa.Column(
            "inquest_outcome_id",
            sa.Enum(
                "ACCIDENT_OR_MISADVENTURE",
                "ALCOHOL_OR_DRUGS_RELATED",
                "INDUSTRIAL_DISEASE",
                "NARRATIVE_CONCLUSION",
                "NATURAL_CAUSES",
                "OPEN_CONCLUSION",
                "ROAD_TRAFFIC_COLLISION",
                "STILLBIRTH",
                "SUICIDE",
                "UNLAWFUL_OR_LAWFUL_KILLING",
                name="inquestoutcomeid",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claim.claim_id"],
        ),
        sa.PrimaryKeyConstraint("claim_inquest_outcome_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("claim_inquest_outcome")
    sa.Enum(name="inquestoutcomeid").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
