"""Create new laa_reference field in application

Revision ID: d2aca39c7115
Revises: 6001ea88742d
Create Date: 2026-08-24 12:15:04.719693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd2aca39c7115'
down_revision: Union[str, None] = '6001ea88742d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('new_laa_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_unique_constraint(None, 'application', ['new_laa_reference'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application', type_='unique')
    op.drop_column('application', 'new_laa_reference')
    # ### end Alembic commands ###
