"""Create new laa_reference field in application

Revision ID: d2aca39c7115
Revises: b2f4c6a8d0e1
Create Date: 2026-08-24 12:15:04.719693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.orm import Session
from sqlalchemy import text

from app.adapters.application_repository_adapter import ApplicationRepositoryAdapter


# revision identifiers, used by Alembic.
revision: str = 'd2aca39c7115'
down_revision: Union[str, None] = 'b2f4c6a8d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Add the column as nullable
    op.add_column('application', sa.Column('new_laa_reference', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=True))
    
    # Step 2: Populate new_laa_reference for existing applications
    bind = op.get_bind()
    session = Session(bind=bind)
    
    # Create an instance of the repository adapter to use its methods
    adapter = ApplicationRepositoryAdapter(session)
    
    # Get all existing applications without a new_laa_reference
    result = session.execute(text("SELECT laa_reference FROM application WHERE new_laa_reference IS NULL"))
    applications = result.fetchall()
    
    # Update each application that doesn't have a new_laa_reference
    for app in applications:
        new_reference = adapter._get_laa_reference()
        
        session.execute(
            text("UPDATE application SET new_laa_reference = :new_ref WHERE laa_reference = :laa_ref"),
            {"new_ref": new_reference, "laa_ref": app[0]}
        )
    
    session.commit()
    
    # Step 3: Make the column NOT NULL
    op.alter_column('application', 'new_laa_reference', nullable=False)
    
    # Step 4: Add unique constraint
    op.create_unique_constraint(None, 'application', ['new_laa_reference'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application', type_='unique')
    op.drop_column('application', 'new_laa_reference')
    # ### end Alembic commands ###
