"""IDDS-292 add claim table

Revision ID: da57ddca1aae
Revises: 02a055ebbdc7
Create Date: 2026-07-07 11:25:38.664442

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "da57ddca1aae"
down_revision: Union[str, None] = "02a055ebbdc7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "claim",
        sa.Column("laa_reference", sa.Integer(), nullable=False),
        sa.Column(
            "claim_type_id",
            sa.Enum("PAYMENT_ON_ACCOUNT", "FINAL_BILL", "NIL_BILL", name="claimtype"),
            nullable=True,
        ),
        sa.Column(
            "status_id",
            sa.Enum(
                "PENDING",
                "ACCEPTED",
                "REJECTED",
                "REJECTED_WITH_AMENDMENT",
                name="claimstatus",
            ),
            nullable=True,
        ),
        sa.Column("submission_date", sa.DateTime(), nullable=False),
        sa.Column("total_profit_cost_net", sa.Integer(), nullable=False),
        sa.Column("total_profit_cost_gross", sa.Integer(), nullable=False),
        sa.Column("claimant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "poa_type_id",
            sa.Enum(
                "PROFIT_COST", "EXPERT_COST", "NON_EXPERT_DISBURSEMENT", name="poatype"
            ),
            nullable=True,
        ),
        sa.Column("claim_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["laa_reference"],
            ["application.laa_reference"],
        ),
        sa.PrimaryKeyConstraint("claim_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("claim")
    # ### end Alembic commands ###
