"""add_provider_to_application

Revision ID: df44b19af78e
Revises: 6b0bce71fdb8
Create Date: 2026-06-10 12:10:48.154934

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "df44b19af78e"
down_revision: Union[str, None] = "6b0bce71fdb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provider",
        sa.Column("firm_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("office_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("provider_id"),
    )
    op.add_column("application", sa.Column("provider_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "application", "provider", ["provider_id"], ["provider_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "application", type_="foreignkey")
    op.drop_column("application", "provider_id")
    op.drop_table("provider")
    # ### end Alembic commands ###
