"""baseline

Revision ID: f85e214f6a32
Revises: 48b9cef7f8a2
Create Date: 2026-05-29 10:03:21.570891

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f85e214f6a32"
down_revision: Union[str, None] = "48b9cef7f8a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client",
        sa.Column(
            "client_first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "client_last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "client_last_name_at_birth",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column("date_of_birth", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "national_insurance_number",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column(
            "correspondence_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("home_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("has_applied_previously", sa.Boolean(), nullable=False),
        sa.Column(
            "prev_application_reference",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("client_id"),
    )
    op.create_table(
        "proceeding",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "proceeding_id",
            sa.Enum(
                "PC049",
                "MN035",
                "MN036",
                "MH028",
                "MH030",
                "IQ001",
                "IQ002",
                "IQ003",
                "IQ004",
                "IQ010",
                "TEST1",
                name="proceedingid",
            ),
            nullable=True,
        ),
        sa.Column(
            "proceeding_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("category_of_law", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "certificate_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "level_of_service", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("matter_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "scope_limitation_heading",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column(
            "scope_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("substantive_cost_limitation", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("proceeding_id"),
    )
    op.create_table(
        "public_body",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "public_body_id",
            sa.Enum(
                "PRIME_MINISTER_OFFICE",
                "CABINET_OFFICE",
                "ATTORNEY_GENERAL",
                "DEPARTMENT_FOR_BUSINESS_AND_TRADE",
                "DEPARTMENT_FOR_CULTURE_MEDIA_AND_SPORT",
                "DEPARTMENT_FOR_EDUCATION",
                "DEPARTMENT_FOR_ENERGY_SECURITY_AND_NET_ZERO",
                "DEPARTMENT_FOR_ENVIRONMENT_FOOD_AND_RURAL_AFFAIRS",
                "DEPARTMENT_FOR_SCIENCE_INNOVATION_AND_TECHNOLOGY",
                "DEPARTMENT_FOR_TRANSPORT",
                "DEPARTMENT_FOR_WORK_AND_PENSIONS",
                "DEPARTMENT_OF_HEALTH_AND_SOCIAL_CARE",
                name="publicbodyid",
            ),
            nullable=True,
        ),
        sa.Column(
            "public_body_description",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_body_id"),
    )
    op.create_table(
        "deceased",
        sa.Column(
            "deceased_first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "deceased_last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "deceased_date_of_birth", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "deceased_date_of_death", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "coroners_reference", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "further_information", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "client_relationship_to_deceased",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column("deceased_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.client_id"],
        ),
        sa.PrimaryKeyConstraint("deceased_id"),
    )
    op.create_table(
        "application",
        sa.Column("laa_reference", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("used_delegated_functions", sa.Boolean(), nullable=False),
        sa.Column(
            "application_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("auto_grant", sa.Boolean(), nullable=True),
        sa.Column(
            "overall_decision", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("deceased_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.client_id"],
        ),
        sa.ForeignKeyConstraint(
            ["deceased_id"],
            ["deceased.deceased_id"],
        ),
        sa.PrimaryKeyConstraint("laa_reference"),
    )
    op.create_table(
        "application_proceeding",
        sa.Column("application_proceeding_id", sa.Integer(), nullable=False),
        sa.Column(
            "client_involvement_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("merits_decision", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("laa_reference", sa.Integer(), nullable=False),
        sa.Column(
            "proceeding_id",
            sa.Enum(
                "PC049",
                "MN035",
                "MN036",
                "MH028",
                "MH030",
                "IQ001",
                "IQ002",
                "IQ003",
                "IQ004",
                "IQ010",
                "TEST1",
                name="proceedingid",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["laa_reference"],
            ["application.laa_reference"],
        ),
        sa.ForeignKeyConstraint(
            ["proceeding_id"],
            ["proceeding.proceeding_id"],
        ),
        sa.PrimaryKeyConstraint("application_proceeding_id"),
    )
    op.create_table(
        "application_public_body",
        sa.Column("application_public_body_id", sa.Integer(), nullable=False),
        sa.Column(
            "public_body_id",
            sa.Enum(
                "PRIME_MINISTER_OFFICE",
                "CABINET_OFFICE",
                "ATTORNEY_GENERAL",
                "DEPARTMENT_FOR_BUSINESS_AND_TRADE",
                "DEPARTMENT_FOR_CULTURE_MEDIA_AND_SPORT",
                "DEPARTMENT_FOR_EDUCATION",
                "DEPARTMENT_FOR_ENERGY_SECURITY_AND_NET_ZERO",
                "DEPARTMENT_FOR_ENVIRONMENT_FOOD_AND_RURAL_AFFAIRS",
                "DEPARTMENT_FOR_SCIENCE_INNOVATION_AND_TECHNOLOGY",
                "DEPARTMENT_FOR_TRANSPORT",
                "DEPARTMENT_FOR_WORK_AND_PENSIONS",
                "DEPARTMENT_OF_HEALTH_AND_SOCIAL_CARE",
                name="publicbodyid",
            ),
            nullable=False,
        ),
        sa.Column("laa_reference", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["laa_reference"],
            ["application.laa_reference"],
        ),
        sa.ForeignKeyConstraint(
            ["public_body_id"],
            ["public_body.public_body_id"],
        ),
        sa.PrimaryKeyConstraint("application_public_body_id"),
    )
    op.drop_table("cases")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cases",
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "category",
            postgresql.ENUM(
                "asylum",
                "crime",
                "debt",
                "family",
                "housing",
                "welfare",
                name="category",
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "exceptional_funding", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("cases_pkey")),
    )
    op.drop_table("application_public_body")
    op.drop_table("application_proceeding")
    op.drop_table("application")
    op.drop_table("deceased")
    op.drop_table("public_body")
    op.drop_table("proceeding")
    op.drop_table("client")
    # ### end Alembic commands ###
