"""Add CASE_NOTE_ADDED to historyeventreference enum

Revision ID: fa5e3308e150
Revises: 6001ea88742d
Create Date: 2026-08-26 17:00:31.718556

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa5e3308e150"
down_revision: str | None = "6001ea88742d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "historyeventreference",
        [
            "APPLICATION_ASSESSMENT_COMPLETED",
            "APPLICATION_GRANTED_EMAIL",
            "APPLICATION_GRANTED_LETTER",
            "APPLICATION_REFUSED",
            "APPLICATION_SUBMISSION_CONFIRMATION",
            "APPLICATION_SUBMITTED",
            "CERTIFICATE_CREATED",
            "CLAIM_APPROVED_EMAIL",
            "CLAIM_ASSESSMENT_COMPLETED",
            "CLAIM_REJECTED_EMAIL",
            "CLAIM_SUBMISSION_CONFIRMATION",
            "CLAIM_SUBMITTED",
            "INTERESTED_PARTY_UPDATED",
            "POA_AUTO_APPROVED",
            "POA_AUTO_REJECTED",
        ],
        [
            "APPLICATION_ASSESSMENT_COMPLETED",
            "APPLICATION_GRANTED_EMAIL",
            "APPLICATION_GRANTED_LETTER",
            "APPLICATION_REFUSED",
            "APPLICATION_SUBMISSION_CONFIRMATION",
            "APPLICATION_SUBMITTED",
            "CASE_NOTE_ADDED",
            "CERTIFICATE_CREATED",
            "CLAIM_APPROVED_EMAIL",
            "CLAIM_ASSESSMENT_COMPLETED",
            "CLAIM_REJECTED_EMAIL",
            "CLAIM_SUBMISSION_CONFIRMATION",
            "CLAIM_SUBMITTED",
            "INTERESTED_PARTY_UPDATED",
            "POA_AUTO_APPROVED",
            "POA_AUTO_REJECTED",
        ],
        [("history_event", "event_reference")],
        False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "historyeventreference",
        [
            "APPLICATION_ASSESSMENT_COMPLETED",
            "APPLICATION_GRANTED_EMAIL",
            "APPLICATION_GRANTED_LETTER",
            "APPLICATION_REFUSED",
            "APPLICATION_SUBMISSION_CONFIRMATION",
            "APPLICATION_SUBMITTED",
            "CASE_NOTE_ADDED",
            "CERTIFICATE_CREATED",
            "CLAIM_APPROVED_EMAIL",
            "CLAIM_ASSESSMENT_COMPLETED",
            "CLAIM_REJECTED_EMAIL",
            "CLAIM_SUBMISSION_CONFIRMATION",
            "CLAIM_SUBMITTED",
            "INTERESTED_PARTY_UPDATED",
            "POA_AUTO_APPROVED",
            "POA_AUTO_REJECTED",
        ],
        [
            "APPLICATION_ASSESSMENT_COMPLETED",
            "APPLICATION_GRANTED_EMAIL",
            "APPLICATION_GRANTED_LETTER",
            "APPLICATION_REFUSED",
            "APPLICATION_SUBMISSION_CONFIRMATION",
            "APPLICATION_SUBMITTED",
            "CERTIFICATE_CREATED",
            "CLAIM_APPROVED_EMAIL",
            "CLAIM_ASSESSMENT_COMPLETED",
            "CLAIM_REJECTED_EMAIL",
            "CLAIM_SUBMISSION_CONFIRMATION",
            "CLAIM_SUBMITTED",
            "INTERESTED_PARTY_UPDATED",
            "POA_AUTO_APPROVED",
            "POA_AUTO_REJECTED",
        ],
        [("history_event", "event_reference")],
        True,
    )
    # ### end Alembic commands ###
