apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "laa-inquests-api.fullname" . }}-auto-approve-poa-emails
  labels:
    {{- include "laa-inquests-api.labels" . | nindent 4 }}
spec:
  schedule: "0 9 * * *"
  timeZone: "Europe/London"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        metadata:
          labels:
            {{- include "laa-inquests-api.selectorLabels" . | nindent 12 }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "laa-inquests-api.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          restartPolicy: OnFailure
          containers:
            - name: {{ .Chart.Name }}-auto-approve-poa-emails
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["python", "bin/send_auto_approved_poa_emails.py"]
              env:
                {{ include "laa-inquests-api.app.vars" . | nindent 16 }}
                {{ include "laa-inquests-api.app.secrets" . | nindent 16 }}
