from typing import Protocol


class ProviderDetailsPort(Protocol):
    def get_firm_name(self, firm_code: str) -> str | None: ...
    def get_office_email(self, firm_code: str, office_code: str) -> str | None: ...
