name: Test

on: workflow_call

jobs:
  test:
    name: Pytest
    environment: uat
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Set environment variables
      shell: bash
      run: |
        echo "GOV_NOTIFY_API_KEY=${{ inputs.gov-notify-api-key || ''}}" >> $GITHUB_ENV
        echo "GOV_NOTIFY_APPLICATION_SUBMIT_TEMPLATE_ID=${{ inputs.gov-notify-application-submit-template-id || ''}}" >> $GITHUB_ENV
        echo "GOV_NOTIFY_CALLBACK_BEARER_TOKEN=${{ inputs.gov-notify-callback-bearer-token || ''}}" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install -r requirements/generated/requirements-testing.txt --upgrade pip

    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        coverage run -m pytest
        coverage xml
      env:
        GOV_NOTIFY_API_KEY: ${{ env.GOV_NOTIFY_API_KEY }}
        GOV_NOTIFY_APPLICATION_SUBMIT_TEMPLATE_ID: ${{ env.GOV_NOTIFY_APPLICATION_SUBMIT_TEMPLATE_ID }}
        GOV_NOTIFY_CALLBACK_BEARER_TOKEN: ${{ env.GOV_NOTIFY_CALLBACK_BEARER_TOKEN }}

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-xml-report
        path: coverage.xml